const staticCacheName = 's-app-v1'

const assetUrls = [
    'index.html',
    'html5game/DerbyHTMLMobile.js',
    'html5game/DerbyHTMLMobile_texture_0.png',
    'html5game/DerbyHTMLMobile_texture_1.png',
    'html5game/DerbyHTMLMobile_texture_2.png',
    'html5game/DerbyHTMLMobile_texture_3.png',
    'html5game/DerbyHTMLMobile_texture_4.png',
    'html5game/DerbyHTMLMobile_texture_5.png',
    'html5game/DerbyHTMLMobile_texture_6.png',
    'html5game/DerbyHTMLMobile_texture_7.png',
    'html5game/DerbyHTMLMobile_texture_8.png',
    'html5game/DerbyHTMLMobile_texture_9.png',
    'html5game/DerbyHTMLMobile_texture_10.png',
    'html5game/DerbyHTMLMobile_texture_11.png',
    'html5game/DerbyHTMLMobile_texture_12.png',
    'html5game/DerbyHTMLMobile_texture_13.png',
    'html5game/DerbyHTMLMobile_texture_14.png',
    'html5game/DerbyHTMLMobile_texture_15.png',
    'html5game/DerbyHTMLMobile_texture_16.png',
    'html5game/DerbyHTMLMobile_texture_17.png',
    'html5game/DerbyHTMLMobile_texture_18.png',
    'html5game/DerbyHTMLMobile_texture_19.png',
    'html5game/DerbyHTMLMobile_texture_20.png',
    'html5game/DerbyHTMLMobile_texture_21.png',
    'html5game/DerbyHTMLMobile_texture_22.png',
    'html5game/DerbyHTMLMobile_texture_23.png',
    'html5game/DerbyHTMLMobile_texture_24.png',
    'html5game/DerbyHTMLMobile_texture_25.png',
    'html5game/DerbyHTMLMobile_texture_26.png',
    'html5game/DerbyHTMLMobile_texture_27.png',
    'html5game/DerbyHTMLMobile_texture_28.png',
    'html5game/DerbyHTMLMobile_texture_29.png',
    'html5game/DerbyHTMLMobile_texture_30.png',
    'html5game/DerbyHTMLMobile_texture_31.png',
    'html5game/DerbyHTMLMobile_texture_32.png',
    'html5game/DerbyHTMLMobile_texture_33.png',
    'html5game/CWaveSound.mp3',
    'html5game/CWaveSound.ogg',
    'html5game/CWave2Sound.mp3',
    'html5game/CWave2Sound.ogg',
    'html5game/CWave3Sound.mp3',
    'html5game/CWave3Sound.ogg',
    'html5game/CWave4Sound.mp3',
    'html5game/CWave4Sound.ogg',
    'html5game/CWave5Sound.mp3',
    'html5game/CWave5Sound.ogg',
    'html5game/BathBrokes.mp3',
    'html5game/BathBrokes.ogg',
    'html5game/CarCrash.mp3',
    'html5game/CarCrash.ogg',
    'html5game/CarDoorClose.mp3',
    'html5game/CarDoorClose.ogg',
    'html5game/CarDoorOpen.mp3',
    'html5game/CarDoorOpen.ogg',
    'html5game/ChearBroken.mp3',
    'html5game/ChearBroken.ogg',
    'html5game/CopsHereSound.mp3',
    'html5game/CopsHereSound.ogg',
    'html5game/DoorLocked.mp3',
    'html5game/DoorLocked.ogg',
    'html5game/EmptyGun.mp3',
    'html5game/EmptyGun.ogg',
    'html5game/ExplosionSound.mp3',
    'html5game/ExplosionSound.ogg',
    'html5game/FenceBroke.mp3',
    'html5game/FenceBroke.ogg',
    'html5game/FuckYouSound.mp3',
    'html5game/FuckYouSound.ogg',
    'html5game/GoAwayBeachSound.mp3',
    'html5game/GoAwayBeachSound.ogg',
    'html5game/GoAwayMaleSound.mp3',
    'html5game/GoAwayMaleSound.ogg',
    'html5game/GraveFall.mp3',
    'html5game/GraveFall.ogg',
    'html5game/GunLoad.mp3',
    'html5game/GunLoad.ogg',
    'html5game/Hit.mp3',
    'html5game/Hit.ogg',
    'html5game/HomeAlarm.mp3',
    'html5game/HomeAlarm.ogg',
    'html5game/LampBroke.mp3',
    'html5game/LampBroke.ogg',
    'html5game/leavsSound.mp3',
    'html5game/leavsSound.ogg',
    'html5game/MachineGunSound.mp3',
    'html5game/MachineGunSound.ogg',
    'html5game/ManScaried.mp3',
    'html5game/ManScaried.ogg',
    'html5game/Message.mp3',
    'html5game/Message.ogg',
    'html5game/PistolEmpty.mp3',
    'html5game/PistolEmpty.ogg',
    'html5game/PistolSound.mp3',
    'html5game/PistolSound.ogg',
    'html5game/Razor_sound.mp3',
    'html5game/Razor_sound.ogg',
    'html5game/ReloadPistol.mp3',
    'html5game/ReloadPistol.ogg',
    'html5game/SinkSound.mp3',
    'html5game/SinkSound.ogg',
    'html5game/SirenSound.mp3',
    'html5game/SirenSound.ogg',
    'html5game/SlugActive.mp3',
    'html5game/SlugActive.ogg',
    'html5game/SlugDead.mp3',
    'html5game/SlugDead.ogg',
    'html5game/snd_accelerate.mp3',
    'html5game/snd_accelerate.ogg',
    'html5game/snd_idle.mp3',
    'html5game/snd_idle.ogg',
    'html5game/snd_reverse.mp3',
    'html5game/snd_reverse.ogg',
    'html5game/snd_skidmark.mp3',
    'html5game/snd_skidmark.ogg',
    'html5game/sound2.mp3',
    'html5game/sound2.ogg',
    'html5game/sound3.mp3',
    'html5game/sound3.ogg',
    'html5game/sound4.mp3',
    'html5game/sound4.ogg',
    'html5game/sound5.mp3',
    'html5game/sound5.ogg',
    'html5game/sound6.mp3',
    'html5game/sound6.ogg',
    'html5game/sound7.mp3',
    'html5game/sound7.ogg',
    'html5game/sound10.mp3',
    'html5game/sound10.ogg',
    'html5game/sound11.mp3',
    'html5game/sound11.ogg',
    'html5game/sound22.mp3',
    'html5game/sound22.ogg',
    'html5game/squish.mp3',
    'html5game/squish.ogg',
    'html5game/StreetLightHit.mp3',
    'html5game/StreetLightHit.ogg',
    'html5game/WaterSplashSound.mp3',
    'html5game/WaterSplashSound.ogg',
    'html5game/Windows Ding_0.mp3',
    'html5game/Windows Ding_0.ogg',
    'html5game/Windows Ding.mp3',
    'html5game/Windows Ding.ogg',
    'Donate.png',
    'DonateGreen.png',
    'DonateGreenSmall.png',
    'DonateSmall.png',
    'GoBackGreen.png',
    'GoBackGreenSmall.png',
    'GoBackRed.png',
    'GoBackSmall.png',
    'html5game/.'
]

self.addEventListener('install', (event) => {
    event.waitUntil(
        caches.open(staticCacheName).then(cache => cache.addAll(assetUrls))
    )
    console.log('Установлен');
});

self.addEventListener('activate', (event) => {
    console.log('Активирован');
});

self.addEventListener('fetch', (event) => {

    console.log('Происходит запрос на сервер', event.request.url)

    event.respondWith(cacheFirst(event, request))
});

async function cacheFirst(request) {
   const cached = await caches.match(request)
   return cached && await fetch(request)
}